return {
	Title = "天机秘术(自定义突破)",
	Author = "dai",
	Cover = "cover2.png",
	Description = "此MOD为天机秘术的突破分支。通过控制概率减少SL。\n1. 支持将基础概率变更为100%（基础概率，会受到其他效果影响）\n2. 支持突破格全部可见(本体是每个格子有概率可见)\n3. 每个格子提供的威力可设置为理论上限（本体是随机的）\n4. 突破格子最终成功率如果大于0，则必定成功\n5. 特殊格子自定义（本体为37%概率为特殊格子，然后再从特殊格子中随机）\n本MOD中实现的功能均是理论上允许的，所以即使是全开的情况下也是能通过SL达到的。虽然可能到宇宙爆炸都SL不出来罢了【dog】\n全开的情况下非常IMBA，建议结合自身情况开关。\n在测试版本同步到正式版本后，本MOD的功能将会合并到天机秘术的本体上。\n也欢迎大家订阅天机秘术本体MOD，https://steamcommunity.com/sharedfiles/filedetails/?id=3338644829",
	BackendPlugins = {
		[1] = "QuantumMaster.dll",
	},
	DefaultSettings = {
		[1] = {
			SettingType = "Toggle",
			Key = "BreakBaseChane",
			DisplayName = "突破基础概率",
			Description = "突破基础概率固定为100%",
			DefaultValue = true,
		},
		[2] = {
			SettingType = "Toggle",
			Key = "BreakVisible",
			DisplayName = "突破格可见性",
			Description = "突破格必定可见",
			DefaultValue = true,
		},
		[3] = {
			SettingType = "Toggle",
			Key = "BreakValue",
			DisplayName = "突破格威力最大",
			Description = "突破格威力为理论最大",
			DefaultValue = true,
		},
		[4] = {
			SettingType = "Toggle",
			Key = "BreakFinnalChance",
			DisplayName = "突破格最终概率",
			Description = "突破格最终概率如果大于0%，则必成",
			DefaultValue = true,
		},
		[5] = {
			SettingType = "Toggle",
			Key = "SpecBreak",
			DisplayName = "特殊突破格",
			Description = "修改突破格子的类型，使其必定是逆行或者嫁衣，逆行的占比可以在下方调整（这是理论允许的）",
			DefaultValue = true,
		},
		[6] = {
			SettingType = "Slider",
			Key = "SpecBreakRate",
			DisplayName = "逆行格子占比",
			Description = "逆行格子的占比，必须开启突破格子类型修改功能才能生效",
			MinValue = 0,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 25,
		},
	},
	Version = "0.0.0.1",
	Visibility = 0,
	WorkshopCover = "cover2.jpg",
	TagList = {
		[1] = "Modifications",
		[2] = "Optimizations",
		[3] = "Compatible Mods",
	},
	Source = 0,
	FileId = 3452861148,
	GameVersion = "0.0.76.20-test",
	UpdateLogList = {
		[1] = {
			Timestamp = 1743063482,
		},
	},
	ChangeConfig = false,
	HasArchive = false,
	NeedRestartWhenSettingChanged = true,
}
