return {
    Title = "[测试]天机秘术-十强武者(Reborn)",
    Author = "dai",
    Cover = "cover2.jpg",
    BackendPlugins = {
        "CombatMaster.dll",
    },
    DefaultSettings = {
        {
            SettingType = "Dropdown",
            Key = "CombatLuckyLevel",
            DisplayName = "战斗气运",
            Description = [[选择战斗相关功能的气运等级。
方寸大乱: 心绪彻底失控，招式章法全无，破绽百出，是为武者最凶险之困境。（战斗中各种随机事件极度不利）
患得患失：心神不宁，疑虑丛生，出手之际犹豫不决，难以发挥平日水准。（战斗中各种随机事件比较不利）
气定神闲：内心沉静，呼吸绵长，不起波澜，能如常映照并应对周身万物。（关闭MOD功能，默认游戏体验）
游刃有余：心思通透，举止从容，于刀锋之间亦可寻得转圜之机，把握战局节奏。（战斗中各种随机事件相对有利）
随心所欲：心之所向，身之所往，招无定式却无不契合战机，已达一流高手之境。（战斗中各种随机事件非常有利）
如有神助：灵台空明，如有天启，常能于不可能处觅得生机，发挥超乎自身极限的威力。（战斗中各种随机事件极度有利）
天人合一：神与天会，身与道合，周天万物皆可为援手，诸般变化无不顺心如意。（战斗中各种随机事件几乎必然有利）
万法归一：穷尽世间万法，终悟其源为一。此心即道，此念即理，战果未始而早已注定。（战斗中各种随机事件必然达到理论上限）]],
            Options = {
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 7,
        },        {
            SettingType = "Dropdown",
            Key = "KuangDao",
            DisplayName = "【武者】狂刀",
            Description = "狂刀命中DEBUFF减少",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "LiHeZhi",
            DisplayName = "【武者】离合指",
            Description = "反噬概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "FuYinZhi",
            DisplayName = "【武者】伏阴指",
            Description = "转化旧伤概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "JingGuiFu",
            DisplayName = "【武者】惊鬼符",
            Description = "敌人逃跑概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "MuGongZhou",
            DisplayName = "【武者】木公咒",
            Description = "打断功法概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "JiuChiXiang",
            DisplayName = "【武者】九痴香",
            Description = "敌人功法打断概率增加，自身功法被打断概率减少",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "SuiSuoYu",
            DisplayName = "【武者】随所欲",
            Description = "随所欲获得真气概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "QianNianZui",
            DisplayName = "【武者】千年醉",
            Description = "千年醉获得的几率增益增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "FengGouQuan",
            DisplayName = "【武者】疯狗拳",
            Description = "疯狗拳获得增伤的概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "LingLiuXu",
            DisplayName = "【武者】凌六虚",
            Description = "凌六虚命中要害概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "GuiYeKu",
            DisplayName = "【武者】鬼夜哭",
            Description = "反击成功后的特效触发概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "WuChangJiao",
            DisplayName = "【武者】无常脚",
            Description = "威力提高概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "ZuiBaXianBu",
            DisplayName = "【武者】醉八仙步",
            Description = "获得BUFF概率提高",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "TaiSuJueShou",
            DisplayName = "【武者】太素绝手",
            Description = "打断施展功法概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "QingNvLvBing",
            DisplayName = "【武者】青女履冰",
            Description = "复读概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "XiaoZongYueGong",
            DisplayName = "【武者】小纵跃功",
            Description = "不消耗脚力概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "YueNvJianFa",
            DisplayName = "【武者】越女剑法",
            Description = "越女剑法提供的追击几率提升",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "JingHuaShuiYue",
            DisplayName = "【武者】镜花水月",
            Description = "镜花水月绝对化解的概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "FengMoZuiQuan",
            DisplayName = "【武者】疯魔醉拳",
            Description = "疯魔醉拳复读概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "JieQingKuaiJian",
            DisplayName = "【武者】界青快剑",
            Description = "界青快剑重复触发概率增加（理论上最多连发3次，加上主动释放的话一共4次）",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "XinWuDingYi",
            DisplayName = "【武者】心无定意",
            Description = "心无定意获得式或者减少式消耗的效果生效概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "AoWangShenTui",
            DisplayName = "【武者】鳌王神腿",
            Description = "发动伤害的几率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "YuZhenShu",
            DisplayName = "【武者】逆御针术",
            Description = "获得变招几率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "ManTianHuaYuShi",
            DisplayName = "【武者】漫天花雨式",
            Description = "额外封穴/破绽概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "JiuSiLiHunShou",
            DisplayName = "【武者】九死离魂手",
            Description = "九死离魂手触发秘闻概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "LeiZuBoJianShi",
            DisplayName = "【武者】嫘祖剥茧式",
            Description = "嫘祖剥茧式脱装备的概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Toggle",
            Key = "LeiZuBoJianShiCloth",
            DisplayName = "【开关】嫘祖剥茧式",
            Description = "嫘祖剥茧式脱装备时，是否优先脱外观的衣服",
            DefaultValue = true,
        },
        {
            SettingType = "Dropdown",
            Key = "YaoJiYunYuShi",
            DisplayName = "【武者】瑶姬云雨式",
            Description = "瑶姬云雨式爱慕概率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "BaiCaoQueZhuoZhi",
            DisplayName = "【武者】百草雀啄灸",
            Description = "恢复自身/恶化敌人几率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "JinDaoHuanZhangGong",
            DisplayName = "【武者】金刀换掌功",
            Description = "必然化解几率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "BoDaShiBaShi",
            DisplayName = "【武者】逆跛打八十式",
            Description = "获得变招几率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Dropdown",
            Key = "ShiBaDianQiMeiGun",
            DisplayName = "【武者】逆十八点齐眉棍",
            Description = "获得变招几率增加",
            Options = {
                "跟随全局",
                "方寸大乱",
                "患得患失",
                "气定神闲",
                "游刃有余",
                "随心所欲",
                "如有神助",
                "天人合一",
                "万法归一"
            },
            DefaultValue = 0,
        }
    },
}