return {
    Title = "[测试]天机秘术-气运之子(Reborn)",
    Author = "dai",
    Cover = "cover2.jpg",
    BackendPlugins = {
        "QuantumMaster.dll",
    },
    DefaultSettings = {
        {
            SettingType = "Dropdown",
            Key = "LuckyLevel",
            DisplayName = "气运",
            Description = [[选择自己气运，不同的气运有不同的效果。
目前功能还在编写中，只有在描述中注明【气运】的功能，才会受到气运的影响
命途多舛: 做任何事情都极度容易失败，获取的随机收益都会巨幅减少
时运不济：做任何事情都非常容易失败，获取的随机收益都会中幅减少
顺风顺水：关闭本MOD
左右逢源：做任何事情都相对容易成功，获取的随机收益都会小幅增加
心想事成：做任何事情都非常容易成功，获取的随机收益都会中幅增加
福星高照：做任何事情都极度容易成功，获取的随机收益都会大幅增加
洪福齐天：做任何事情都几乎一定成功，获取的随机收益都会巨幅增加
气运之子：做任何事情都必然一定成功，获取的随机收益都是理论上限（概率为0的情况下无效）]],
            Options = {
                "命途多舛",
                "时运不济",
                "顺风顺水",
                "左右逢源",
                "心想事成",
                "福星高照",
                "洪福齐天",
                "气运之子"
            },
            DefaultValue = 7,
        },
        {
            SettingType = "Toggle",
            Key = "steal",
            DisplayName = "【气运】偷窃",
            Description = "【气运】太吾发起偷窃时成功概率根据气运增加，他人对太吾偷窃时成功概率根据气运减少",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "scam",
            DisplayName = "【气运】唬骗",
            Description = "【气运】太吾发起唬骗时成功概率根据气运增加，他人对太吾唬骗时成功概率根据气运减少",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "rob",
            DisplayName = "【气运】抢劫",
            Description = "【气运】太吾发起抢劫时成功概率根据气运增加，他人对太吾抢劫时成功概率根据气运减少",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "stealLifeSkill",
            DisplayName = "【气运】偷学生活技能",
            Description = "【气运】太吾偷学生活技能时成功概率根据气运增加，他人对太吾偷学时成功概率根据气运减少",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "stealCombatSkill",
            DisplayName = "【气运】偷学战斗技能",
            Description = "【气运】太吾偷学战斗技能时成功概率根据气运增加，他人对太吾偷学时成功概率根据气运减少",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "poison",
            DisplayName = "【气运】下毒",
            Description = "【气运】太吾发起下毒时成功概率根据气运增加，他人对太吾下毒时成功概率根据气运减少",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "plotHarm",
            DisplayName = "【气运】暗害",
            Description = "【气运】太吾发起暗害时成功概率根据气运增加，他人对太吾暗害时成功概率根据气运减少",
            DefaultValue = true,
        },
        {
            SettingType = "Slider",
            Key = "genderControl",
            DisplayName = "生成性别控制",
            Description = "生成角色时，如果是随机的性别，则按照选择进行修改。对于指定性别的NPC生成无效。这个选项控制的是男性的概率，女性的概率就是100%减去男性的概率。（此处控制的是真实性别）",
			MinValue = 0,
			MaxValue = 100,
			StepSize = 1,
			DefaultValue = 50,
        },
        {
            SettingType = "Dropdown",
            Key = "sexualOrientationControl",
            DisplayName = "性取向控制",
            Description = "太吾世界中每个人在诞生的时候都有20%概率是双性恋，可以通过此设置控制所有人（包括开启这个功能之前出生的人）的性取向。性取向会影响表白结婚之类的概率。",
            Options = {
                "关闭功能",
                "全体双性恋",
                "禁止双性恋"
            },
            DefaultValue = 0,
        },
        {
            SettingType = "Toggle",
            Key = "CreateBuildingArea",
            DisplayName = "【气运】世界初始建筑",
            Description = "【气运】生成世界时，产业中的建筑和资源点的初始等级，以及生成数量",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "ropeOrSword",
            DisplayName = "绑人/剑柄救人",
            Description = "事件触发时，如果概率不为0，绳子绑架或者煎饼救人必定成功",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "collectResource",
            DisplayName = "【气运】采集资源引子",
            Description = "【气运】采集资源时必定获取引子，且是可能获取的最高级的引子",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "GetCollectResourceAmount",
            DisplayName = "【气运】采集资源数量",
            Description = "【气运】采集数量必定为浮动区间的上限",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "OfflineUpdateShopManagement",
            DisplayName = "【气运】太吾村经营",
            Description = "【气运】事件触发时，如果概率不为0，产业建筑经营、招募必然成功、村民技艺必定提升",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "ApplyLifeSkillCombatResult",
            DisplayName = "【气运】教艺读书&周天",
            Description = "【气运】事件触发时，如果概率不为0，较艺读书&周天必定触发",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "CalcReadInCombat",
            DisplayName = "【气运】战斗读书",
            Description = "【气运】事件触发时，如果概率不为0，战斗读书必定触发",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "CalcQiQrtInCombat",
            DisplayName = "【气运】战斗周天运转",
            Description = "【气运】事件触发时，如果概率不为0，战斗中周天运转必定触发",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "CalcLootItem",
            DisplayName = "【气运】战利品概率",
            Description = "【气运】事件触发时，如果概率不为0，战利品掉落判定必定通过（原本逻辑是对每个战利品进行判断是否掉落）",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "InitPathContent",
            DisplayName = "【气运】奇遇收获",
            Description = "【气运】奇遇收获资源时，数量为浮动区间的上限",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "GetStrategyProgressAddValue",
            DisplayName = "【气运】读书进度策略",
            Description = "【气运】读书策略（独见独知）进度增加为浮动区间的上限",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "ApplyImmediateReadingStrategyEffectForLifeSkill",
            DisplayName = "【气运】技艺读书效率策略",
            Description = "【气运】技艺书籍的效率增加策略（奇思妙想）进度增加为浮动区间的上限值",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "ParallelUpdateOnMonthChange",
            DisplayName = "【气运】过月地块资源恢复",
            Description = "【气运】地块每月资源恢复数量为浮动区间的上限",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "OfflineCalcGeneralAction_TeachSkill",
            DisplayName = "【气运】太吾受到指点的成功率",
            Description = "【气运】如果太吾受到NPC指点，指点的成功率根据气运增加",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "CatchCricket",
            DisplayName = "抓蛐蛐捕捉成功率",
            Description = "抓蛐蛐必定成功",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "InitResources",
            DisplayName = "初始生成地格资源最大",
            Description = "生成世界时，每个地块上的资源为浮动区间的最大值以及地块上当前可采集的资源，受到难度的影响",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "CheckCricketIsSmart",
            DisplayName = "蛐蛐升级成功率",
            Description = "蛐蛐是否可以升级，如果符合条件必定升级",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "GetCurrReadingEventBonusRate",
            DisplayName = "灵光一闪",
            Description = "灵光一闪概率不为0时，必定灵光一闪",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "GeneratePageIncompleteState",
            DisplayName = "生成书籍参数",
            Description = "生成书籍时，完整的书页为浮动区间的最大值，亡佚书页为浮动区间最小值",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "FixedPagePos",
            DisplayName = "完整书页固定靠前",
            Description = "需要开启生成书籍参数的功能，开启这个功能完整的书页会出现在书本的前篇位置",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "CricketInitialize",
            DisplayName = "健康的蛐蛐",
            Description = "生成蛐蛐时，必定生成耐久上限为理论上限值的，不受伤的蛐蛐",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "CalcNeigongLoopingEffect",
            DisplayName = "【气运】周天内力获取",
            Description = "【气运】周天运转时，获得的内力为浮动区间的最大值",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "GetQiArtStrategyDeltaNeiliBonus",
            DisplayName = "【气运】周天内力策略收益最大",
            Description = "【气运】周天运转时，通过策略获得的内力为浮动区间的最大值",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "TryAddLoopingEvent",
            DisplayName = "天人感应",
            Description = "如果概率不为0，尝试触发天人感应时必定成功",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "ChoosyGetMaterial",
            DisplayName = "【气运】精挑细选品质升级",
            Description = "【气运】精挑细选时，品质升级机制只要概率不是0，则必定生效（不是每次都获取最高品素材）",
            DefaultValue = true,
        },
        {
            SettingType = "Toggle",
            Key = "AddChoosyRemainUpgradeData",
            DisplayName = "【气运】精挑细选过月累计最大",
            Description = "【气运】精挑细选时，每个月都会增加精挑细选的升级概率和数量，这个增加的数值是随机的，开启后可以让增加的数值为理论上限",
            DefaultValue = true,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect1",
            DisplayName = "读书策略，第一个策略指定",
            Description = "第一个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 1,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect2",
            DisplayName = "读书策略，第二个策略指定",
            Description = "第二个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 1,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect3",
            DisplayName = "读书策略，第三个策略指定",
            Description = "第三个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 1,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect4",
            DisplayName = "读书策略，第四个策略指定",
            Description = "第四个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 3,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect5",
            DisplayName = "读书策略，第五个策略指定",
            Description = "第五个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 3,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect6",
            DisplayName = "读书策略，第六个策略指定",
            Description = "第六个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 3,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect7",
            DisplayName = "读书策略，第七个策略指定",
            Description = "第七个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 5,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect8",
            DisplayName = "读书策略，第八个策略指定",
            Description = "第八个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 5,
        },
        {
            SettingType = "Dropdown",
            Key = "BookStrategiesSelect9",
            DisplayName = "读书策略，第九个策略指定",
            Description = "第九个策略指定",
            Options = {
                "使用原版",
                "口诵心惟",
                "行思坐忆",
                "独见独知",
                "奇思妙想",
                "照猫画虎",
                "按图索骥",
                "寻章摘句",
                "含英咀华",
                "温故知新",
                "融会贯通",
                "枕经席文",
                "十行俱下",
                "春诵夏弦",
                "推敲化演",
                "心领得间",
                "迁思回虑",
                "囫囵吞枣",
                "大智若愚",
                "义父注解",
            },
            DefaultValue = 5,
        },
        {
            SettingType = "Toggle",
            Key = "SetSectMemberApproveTaiwu",
            DisplayName = "门派初始支持度",
            Description = "太吾第一次向门派发出拜帖的时候，会默认获取部分人的支持度，具体的人员是随机的，开启后会获取尽可能高品人员的支持度。理论上这获取的支持度会更高",
            DefaultValue = true,
        }
    },
}